### PR TITLE
[WIP] Translate docs to Chinese

### PR DESCRIPTION
**Pull request by krwu**
I'm working on it.

- Overview
    - [x] About Framework
    - [x] Contributing
    - [x] Versioning
    - [x] LICENSE
- Getting Started
    - [x] Installation
    - [x] Application Lifecycle
    - [x] Directory Structure
    - [x] Configuration
    - [x] Console Commands
- The Basics
    - [x] Quick Start
    - [x] Scaffolding
    - [x] Prototyping
- Framework
    - [x] Design Approach
    - [x] Application Server
    - [x] Kernel and Environment
    - [x] Container and Factories
    - [x] Bootloaders
    - [x] Config Objects
    - [x] IoC scopes
    - [x] Static Memory
    - [x] Finalizers
- Cookbook
    - [x] Annotated Routing
    - [x] Domain Core and Controllers
    - [x] Container Injectors 
    - [x] Integrate Golang service to PHP
    - [x] Custom Dispatcher
- Components
    - [x] Files and Directories
    - [x] Code Generation
    - [x] Static Analysis Tools
    - [x] Prometheus Metrics
    - [x] Data Grids
- Console
    - [x] Installation and Configuration
    - [x] User Commands
- HTTP
    - [x] Installation and Configuration
    - [x] Request Lifecycle
    - [x] Request and Response
    - [x] Routing
    - [x] Error Pages
    - [x] Middleware
    - [x] Golang Middleware
    - [x] Cookies
    - [x] Session
    - [x] CSRF protection
    - [x] Custom PSR-15 Handlers
- Security
    - [x] Data Encryption
    - [x] Validation Interfaces
    - [x] Role Based Access Control
    - [x] User Authentication
- Request Validation
    - [x] Installation and Configuration
    - [x] Filter Object
    - [x] Composite Filters
- Databases
    - [x] Installation and Configuration
    - [x] Access Database
    - [x] Database Isolation
    - [x] Query Builders
    - [ ] Transactions
    - [ ] Schema Introspection
    - [ ] Schema Declaration
    - [ ] Migrations
    - [ ] Errata
- Cycle ORM
    - [ ] Installation and Configuration
    - [ ] Transactions
    - [ ] Without Annotations
    - [ ] Full Documentation
    - [ ] Console Commands
- Queue and Jobs
    - [ ] Installation and Configuration
    - [ ] Console Commands
    - [ ] Running Jobs
    - [ ] Standalone Usage
    - [x] Website Scraper
- Views
    - [ ] Installation and Configuration
    - [ ] Rendering Views
    - [ ] Plain PHP templates
    - [ ] Twig templates
- Stempler Templating
    - [ ] Installation and Configuration
    - [ ] Basic Usage
    - [ ] Directives
    - [ ] Inheritance and Stacks
    - [ ] Components and Props
    - [ ] Advancing DSL
    - [ ] AST Modifications
- Internalization
    - [ ] Installation and Configuration
    - [ ] Import and Export
    - [ ] View Localization
    - [ ] Say Trait
- GRPC
    - [ ] Installation and Configuration
    - [ ] Service Code
    - [ ] Client SDK
    - [ ] Golang Services
    - [ ] Data Streaming
- Event Broadcasting
    - [ ] Installation and Configuration
    - [ ] Publish and Consume
    - [ ] WebSockets
- Debug and Profiling
    - [ ] Dumping Variables
    - [ ] XDebug
    - [ ] Handling Exceptions
- Extensions
    - [ ] Code Style
    - [ ] Dotenv   
    - [ ] Monolog
    - [ ] Sentry

### CODE REVIEW

**Comment by wolfy-j** [comment]
Make sure to rename in manifest as well as it used to configure navigation

**Comment by krwu** [comment]
> Make sure to rename in manifest as well as it used to configure navigation

Do you mean the docs engine will use `zh_CN/manifest.json` to render the navigation?

I will do it when the rest documents were completed.

**Comment by wolfy-j** [comment]
Correct

**Comment by 48d90782** [comment]
Hey @krwu :) Just a friendly ping. Are you still planning to finish the translation?

**Comment by wolfy-j** [comment]
I think it's OK to keep it open. People will notice it then.

**Pull request closed without merging**
